// afrog 扫描能力服务协议。
//
// 本文件是 docs/plan/afrog-grpc-protocol.md 第 6 节 proto 草案的落地实现，
// 两者必须逐字对应：字段名、编号、语义一律不得私自改动。
// 重新生成代码：cd proto/afrog/v1 && go generate ./...

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: afrog.proto

package afrogv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AfrogScanner_SubmitScan_FullMethodName       = "/afrog.v1.AfrogScanner/SubmitScan"
	AfrogScanner_StreamEvents_FullMethodName     = "/afrog.v1.AfrogScanner/StreamEvents"
	AfrogScanner_GetStatus_FullMethodName        = "/afrog.v1.AfrogScanner/GetStatus"
	AfrogScanner_GetResults_FullMethodName       = "/afrog.v1.AfrogScanner/GetResults"
	AfrogScanner_Control_FullMethodName          = "/afrog.v1.AfrogScanner/Control"
	AfrogScanner_ListCapabilities_FullMethodName = "/afrog.v1.AfrogScanner/ListCapabilities"
)

// AfrogScannerClient is the client API for AfrogScanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 公开接口（第三方语言 / 未来 MCP 适配层） ====================
type AfrogScannerClient interface {
	SubmitScan(ctx context.Context, in *SubmitScanRequest, opts ...grpc.CallOption) (*SubmitScanResponse, error)
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error)
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error)
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error)
}

type afrogScannerClient struct {
	cc grpc.ClientConnInterface
}

func NewAfrogScannerClient(cc grpc.ClientConnInterface) AfrogScannerClient {
	return &afrogScannerClient{cc}
}

func (c *afrogScannerClient) SubmitScan(ctx context.Context, in *SubmitScanRequest, opts ...grpc.CallOption) (*SubmitScanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitScanResponse)
	err := c.cc.Invoke(ctx, AfrogScanner_SubmitScan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afrogScannerClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AfrogScanner_ServiceDesc.Streams[0], AfrogScanner_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, ScanEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfrogScanner_StreamEventsClient = grpc.ServerStreamingClient[ScanEvent]

func (c *afrogScannerClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AfrogScanner_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afrogScannerClient) GetResults(ctx context.Context, in *GetResultsRequest, opts ...grpc.CallOption) (*GetResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultsResponse)
	err := c.cc.Invoke(ctx, AfrogScanner_GetResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afrogScannerClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, AfrogScanner_Control_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afrogScannerClient) ListCapabilities(ctx context.Context, in *ListCapabilitiesRequest, opts ...grpc.CallOption) (*ListCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapabilitiesResponse)
	err := c.cc.Invoke(ctx, AfrogScanner_ListCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AfrogScannerServer is the server API for AfrogScanner service.
// All implementations must embed UnimplementedAfrogScannerServer
// for forward compatibility.
//
// ==================== 公开接口（第三方语言 / 未来 MCP 适配层） ====================
type AfrogScannerServer interface {
	SubmitScan(context.Context, *SubmitScanRequest) (*SubmitScanResponse, error)
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ScanEvent]) error
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error)
	Control(context.Context, *ControlRequest) (*ControlResponse, error)
	ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error)
	mustEmbedUnimplementedAfrogScannerServer()
}

// UnimplementedAfrogScannerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAfrogScannerServer struct{}

func (UnimplementedAfrogScannerServer) SubmitScan(context.Context, *SubmitScanRequest) (*SubmitScanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitScan not implemented")
}
func (UnimplementedAfrogScannerServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[ScanEvent]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedAfrogScannerServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAfrogScannerServer) GetResults(context.Context, *GetResultsRequest) (*GetResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResults not implemented")
}
func (UnimplementedAfrogScannerServer) Control(context.Context, *ControlRequest) (*ControlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedAfrogScannerServer) ListCapabilities(context.Context, *ListCapabilitiesRequest) (*ListCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCapabilities not implemented")
}
func (UnimplementedAfrogScannerServer) mustEmbedUnimplementedAfrogScannerServer() {}
func (UnimplementedAfrogScannerServer) testEmbeddedByValue()                      {}

// UnsafeAfrogScannerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfrogScannerServer will
// result in compilation errors.
type UnsafeAfrogScannerServer interface {
	mustEmbedUnimplementedAfrogScannerServer()
}

func RegisterAfrogScannerServer(s grpc.ServiceRegistrar, srv AfrogScannerServer) {
	// If the following call pancis, it indicates UnimplementedAfrogScannerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AfrogScanner_ServiceDesc, srv)
}

func _AfrogScanner_SubmitScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogScannerServer).SubmitScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogScanner_SubmitScan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogScannerServer).SubmitScan(ctx, req.(*SubmitScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfrogScanner_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AfrogScannerServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, ScanEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfrogScanner_StreamEventsServer = grpc.ServerStreamingServer[ScanEvent]

func _AfrogScanner_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogScannerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogScanner_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogScannerServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfrogScanner_GetResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogScannerServer).GetResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogScanner_GetResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogScannerServer).GetResults(ctx, req.(*GetResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfrogScanner_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogScannerServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogScanner_Control_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogScannerServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfrogScanner_ListCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogScannerServer).ListCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogScanner_ListCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogScannerServer).ListCapabilities(ctx, req.(*ListCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AfrogScanner_ServiceDesc is the grpc.ServiceDesc for AfrogScanner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AfrogScanner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afrog.v1.AfrogScanner",
	HandlerType: (*AfrogScannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitScan",
			Handler:    _AfrogScanner_SubmitScan_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AfrogScanner_GetStatus_Handler,
		},
		{
			MethodName: "GetResults",
			Handler:    _AfrogScanner_GetResults_Handler,
		},
		{
			MethodName: "Control",
			Handler:    _AfrogScanner_Control_Handler,
		},
		{
			MethodName: "ListCapabilities",
			Handler:    _AfrogScanner_ListCapabilities_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _AfrogScanner_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "afrog.proto",
}

const (
	AfrogAgent_Register_FullMethodName = "/afrog.v1.AfrogAgent/Register"
	AfrogAgent_Connect_FullMethodName  = "/afrog.v1.AfrogAgent/Connect"
)

// AfrogAgentClient is the client API for AfrogAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ==================== 内部接口（节点 ↔ 控制面） ====================
type AfrogAgentClient interface {
	// 用一次性注册令牌换取长期凭据
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// 建立双向流：控制面在流内下发任务/控制，agent 在同一流内回传事件
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ConsoleMessage], error)
}

type afrogAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAfrogAgentClient(cc grpc.ClientConnInterface) AfrogAgentClient {
	return &afrogAgentClient{cc}
}

func (c *afrogAgentClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AfrogAgent_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *afrogAgentClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ConsoleMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AfrogAgent_ServiceDesc.Streams[0], AfrogAgent_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ConsoleMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfrogAgent_ConnectClient = grpc.BidiStreamingClient[AgentMessage, ConsoleMessage]

// AfrogAgentServer is the server API for AfrogAgent service.
// All implementations must embed UnimplementedAfrogAgentServer
// for forward compatibility.
//
// ==================== 内部接口（节点 ↔ 控制面） ====================
type AfrogAgentServer interface {
	// 用一次性注册令牌换取长期凭据
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// 建立双向流：控制面在流内下发任务/控制，agent 在同一流内回传事件
	Connect(grpc.BidiStreamingServer[AgentMessage, ConsoleMessage]) error
	mustEmbedUnimplementedAfrogAgentServer()
}

// UnimplementedAfrogAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAfrogAgentServer struct{}

func (UnimplementedAfrogAgentServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedAfrogAgentServer) Connect(grpc.BidiStreamingServer[AgentMessage, ConsoleMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAfrogAgentServer) mustEmbedUnimplementedAfrogAgentServer() {}
func (UnimplementedAfrogAgentServer) testEmbeddedByValue()                    {}

// UnsafeAfrogAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfrogAgentServer will
// result in compilation errors.
type UnsafeAfrogAgentServer interface {
	mustEmbedUnimplementedAfrogAgentServer()
}

func RegisterAfrogAgentServer(s grpc.ServiceRegistrar, srv AfrogAgentServer) {
	// If the following call pancis, it indicates UnimplementedAfrogAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AfrogAgent_ServiceDesc, srv)
}

func _AfrogAgent_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfrogAgentServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AfrogAgent_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfrogAgentServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AfrogAgent_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AfrogAgentServer).Connect(&grpc.GenericServerStream[AgentMessage, ConsoleMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AfrogAgent_ConnectServer = grpc.BidiStreamingServer[AgentMessage, ConsoleMessage]

// AfrogAgent_ServiceDesc is the grpc.ServiceDesc for AfrogAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AfrogAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "afrog.v1.AfrogAgent",
	HandlerType: (*AfrogAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _AfrogAgent_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AfrogAgent_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "afrog.proto",
}
