version: 2

before:
  hooks:
    - go mod download
    - go mod verify

builds:
  - main: cmd/afrog/main.go
    binary: afrog
    id: afrog
    env:
      - CGO_ENABLED=0
    goos: [windows, linux, darwin]
    goarch: [amd64, arm64]

    flags:
      - -trimpath
      - -pgo=auto
    ldflags:
      - -s
      - -w

archives:
  - formats:
    - zip
    id: afrog
    ids: [afrog]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'

checksum:
  algorithm: sha256
